name: Empty Commit to Keep App Awake

on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

jobs:
  empty-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create empty commit
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git commit --allow-empty -m "Empty commit to keep Streamlit app awake"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:main
