name: Keep Streamlit App Awake

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Create empty commit
        run: |
          git commit --allow-empty -m "Empty commit to keep Streamlit app awake" || echo "Nothing to commit"

      - name: Push commit using PAT
        run: |
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:main
